const cfg=window.CONCURSO_CONFIG;
const peso=Object.fromEntries(cfg.products.map(p=>[p.reporte,p.puntos]));
const productAliases=Object.fromEntries(cfg.products.flatMap(p=>[[p.reporte.toLowerCase(),p.reporte],[p.simple.toLowerCase(),p.reporte]]));
let rows=JSON.parse(localStorage.getItem('avanceConcursoVentas')||'[]');
const $=s=>document.querySelector(s);
const fmt=n=>(Number(n)||0).toLocaleString('es-MX',{maximumFractionDigits:1,minimumFractionDigits:Number.isInteger(Number(n))?0:1});
const imgPath=s=>'assets/managers/'+s;
function save(){localStorage.setItem('avanceConcursoVentas',JSON.stringify(rows));}
function setTab(id){document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));document.querySelector(`[data-tab="${id}"]`).classList.add('active');$('#'+id).classList.add('active');}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
function cutDate(){if(!rows.length)return 'Pendiente de carga';let d=rows.map(r=>r.fecha).sort().pop();return new Date(d+'T00:00:00').toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric'});}
function donaStats(){return cfg.stores.map(s=>{let r=rows.filter(x=>x.tienda===s.tienda&&x.producto==='Dona Grab & Go'&&x.semana>=28&&x.semana<=31);let units=r.reduce((a,b)=>a+b.unidades,0);let days=new Set(r.map(x=>x.fecha)).size;let prom=days?units/days:0;return {...s,units,days,promActual:prom,diff:prom-s.prom};});}
function generalStats(){return cfg.stores.map(s=>{let r=rows.filter(x=>x.tienda===s.tienda&&x.semana>=28&&x.semana<=32);let units=r.reduce((a,b)=>a+b.unidades,0);let points=r.reduce((a,b)=>a+(b.unidades*(peso[b.producto]??1)),0);let max=rows.map(x=>x.fecha).sort().pop();let today=r.filter(x=>x.fecha===max).reduce((a,b)=>a+(b.unidades*(peso[b.producto]??1)),0);return {...s,units,points,today};});}
function kpi(el,arr,mode){let leader=arr.slice().sort((a,b)=>(mode==='dona'?b.diff-a.diff:b.points-a.points))[0]||{};let total=arr.reduce((a,b)=>a+(mode==='dona'?b.units:b.points),0);let avg=arr.reduce((a,b)=>a+(mode==='dona'?b.diff:b.points),0)/(arr.length||1);el.innerHTML=`<div class="kpi"><span>Fecha de corte</span><b>${cutDate()}</b></div><div class="kpi"><span>Líder actual</span><b>${leader.tienda||'Sin avance'}</b></div><div class="kpi"><span>${mode==='dona'?'Unidades Dona':'Puntos acumulados'}</span><b>${fmt(total)}</b></div><div class="kpi"><span>${mode==='dona'?'Dif promedio portafolio':'Promedio puntos'}</span><b>${fmt(avg)}</b></div>`;}
function renderDona(){let arr=donaStats();let sort=$('#sortDona').value;arr.sort((a,b)=>b[sort]-a[sort]);kpi($('#kpisDona'),arr,'dona');let max=Math.max(...arr.map(x=>Math.max(x.diff,0)),1);$('#rankingDona').innerHTML=arr.map((s,i)=>`<article class="card"><div class="rank">${i+1}</div><img class="manager" src="${imgPath(s.img)}"><div class="card-body"><h3 class="store">${s.tienda}</h3><div class="badge">${s.diff>=0?'▲':'▼'} Dif ${fmt(s.diff)}</div><div class="bar"><div class="fill" style="width:${Math.max(4,Math.max(0,s.diff)/max*100)}%"></div></div><div class="metrics"><div class="metric"><small>Base 24-26</small><b>${fmt(s.prom)}</b></div><div class="metric"><small>Prom 28-31</small><b>${fmt(s.promActual)}</b></div><div class="metric"><small>Unidades</small><b>${fmt(s.units)}</b></div></div></div></article>`).join('');}
function renderGeneral(){let arr=generalStats();let sort=$('#sortGeneral').value;arr.sort((a,b)=>b[sort]-a[sort]);kpi($('#kpisGeneral'),arr,'general');let max=Math.max(...arr.map(x=>x.points),1);$('#rankingGeneral').innerHTML=arr.map((s,i)=>`<article class="card"><div class="rank">${i+1}</div><img class="manager" src="${imgPath(s.img)}"><div class="card-body"><h3 class="store">${s.tienda}</h3><div class="badge">${fmt(s.points)} pts</div><div class="bar"><div class="fill" style="width:${Math.max(4,s.points/max*100)}%"></div></div><div class="metrics"><div class="metric"><small>Puntos</small><b>${fmt(s.points)}</b></div><div class="metric"><small>Unidades</small><b>${fmt(s.units)}</b></div><div class="metric"><small>Último día</small><b>${fmt(s.today)}</b></div></div></div></article>`).join('');}
function renderProducts(){$('#productCards').innerHTML=cfg.products.map(p=>`<div class="product"><img src="assets/products/${p.img}"><div><b>${p.simple}</b><span>${p.puntos} punto${p.puntos===1?'':'s'} por pieza</span></div></div>`).join('');}
function renderTable(){let t=$('#dataTable');t.innerHTML='<tr><th>Fecha</th><th>Semana</th><th>Tienda</th><th>Producto</th><th>Unidades</th><th>Puntos</th></tr>'+rows.slice().sort((a,b)=>a.fecha.localeCompare(b.fecha)||a.tienda.localeCompare(b.tienda)).map(r=>`<tr><td>${r.fecha}</td><td>${r.semana}</td><td>${r.tienda}</td><td>${r.producto}</td><td>${fmt(r.unidades)}</td><td>${fmt(r.unidades*(peso[r.producto]??1))}</td></tr>`).join('');}
function renderAll(){$('#cutDate').textContent=cutDate();renderProducts();renderDona();renderGeneral();renderTable();}
function parseCSV(text){let lines=text.trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return[];let sep=lines[0].includes('\t')?'\t':',';let head=lines.shift().split(sep).map(h=>h.trim().toLowerCase());let get=(o,names)=>names.map(n=>o[head.findIndex(h=>h.includes(n))]).find(v=>v!==undefined);
 return lines.map(l=>{let c=l.split(sep).map(x=>x.trim());let prod=(get(c,['producto','ingrediente'])||'').toLowerCase();let producto=productAliases[prod]||get(c,['producto','ingrediente']);return {fecha:get(c,['fecha','dia','día']),semana:Number(get(c,['semana','week'])||0),tienda:get(c,['tienda']),producto,unidades:Number(get(c,['unidad','venta'])||0)}}).filter(r=>r.fecha&&r.tienda&&r.producto&&r.unidades>=0);}
$('#loadCsv').onclick=()=>{let parsed=parseCSV($('#csvInput').value);rows=rows.concat(parsed);save();renderAll();alert(`${parsed.length} filas cargadas`)};
$('#loadSample').onclick=()=>{rows=cfg.sampleRows.slice();save();renderAll();};
$('#clearData').onclick=()=>{if(confirm('¿Limpiar todo el avance cargado?')){rows=[];save();renderAll();}};
$('#exportCsv').onclick=()=>{let csv='fecha,semana,tienda,producto,unidades\n'+rows.map(r=>[r.fecha,r.semana,r.tienda,r.producto,r.unidades].join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='avance_concurso_ventas.csv';a.click();};
$('#sortDona').onchange=renderDona;$('#sortGeneral').onchange=renderGeneral;
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
renderAll();
