const DATA = window.CONTEST_DATA;
const $ = s => document.querySelector(s);
const money = n => Number(n).toLocaleString('es-MX',{maximumFractionDigits:1});
let stores = [...DATA.stores];

function setTabs(){document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));btn.classList.add('active');$('#view-'+btn.dataset.view).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}));}
function renderKpis(){ $('#updatedLabel').textContent=DATA.stats.updated; const k=[['Actualizado',DATA.stats.updated],['Líder',DATA.stats.leader],['Promedio Base',money(DATA.stats.avgBase)],['Promedio Actual',money(DATA.stats.avgActual)],['Diferencia',`${DATA.stats.avgDiff>=0?'+':''}${money(DATA.stats.avgDiff)}`],['Unidades',money(DATA.stats.units)]]; $('#kpis').innerHTML=k.map(x=>`<article class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('');}
function renderCards(list=stores){const max=Math.max(...list.map(s=>Math.abs(s.diff)),1); $('#cards').innerHTML=list.map((s,i)=>{const down=s.diff<0; const width=Math.max(8,Math.min(100,Math.abs(s.diff)/max*100));return `<article class="card ${i===0?'top1':''} ${down?'negative':''}">${i===0?'<div class="crown">👑</div>':''}<div class="rank">${i+1}</div><div class="photoWrap"><img src="${s.image}" alt="${s.store}"></div><div class="cardBody"><h3>${s.store}</h3><div class="diff ${down?'down':''}">${s.diff>=0?'+':''}${money(s.diff)}</div><div class="bar"><i style="width:${width}%"></i></div><div class="miniStats"><div><span>Sem 24-26</span><b>${money(s.base)}</b></div><div><span>Actual</span><b>${money(s.actual)}</b></div></div><div class="pct">${down?'▼':'▲'} ${s.pct>=0?'+':''}${money(s.pct)}% vs. base</div></div></article>`}).join(''); renderChart(list.slice(0,5)); renderLeader(list[0]);}
function renderLeader(s){$('#leaderMini').innerHTML=`<span>Líder actual</span><br><strong>${s.store}</strong><p>Diferencia: ${s.diff>=0?'+':''}${money(s.diff)} vs. Sem 24-26</p>`;}
function renderChart(list){const w=340,h=210,p=28; const vals=list.map(s=>s.diff); const min=Math.min(0,...vals), max=Math.max(1,...vals); const x=i=>p+i*((w-p*2)/(list.length-1||1)); const y=v=>h-p-((v-min)/(max-min||1))*(h-p*2); const pts=vals.map((v,i)=>`${x(i)},${y(v)}`).join(' '); $('#chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Tendencia top 5"><line x1="${p}" y1="${y(0)}" x2="${w-p}" y2="${y(0)}" stroke="#d9e5da" stroke-width="2"/><polyline points="${pts}" fill="none" stroke="#00754a" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>${vals.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="6" fill="#063f2b"/><text x="${x(i)}" y="${h-6}" text-anchor="middle" font-size="10" fill="#60756e" font-weight="800">${i+1}</text>`).join('')}</svg>`;}
function sortBy(mode){stores.sort((a,b)=> mode==='units'?b.units-a.units: mode==='actual'?b.actual-a.actual:b.diff-a.diff); renderCards(stores);} 
setTabs(); renderKpis(); renderCards(); $('#sortMode').addEventListener('change',e=>sortBy(e.target.value));
if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').catch(()=>{});}
