const data = window.CONTEST_DATA || { ranking: [], summary: {}, stores: [] };
const num = new Intl.NumberFormat('es-MX', { maximumFractionDigits: 1, minimumFractionDigits: 1 });
const dateFmt = new Intl.DateTimeFormat('es-MX', { day: '2-digit', month: 'short', year: 'numeric' });
const cutDate = document.getElementById('cutDate');
const kpis = document.getElementById('kpis');
const leaderboard = document.getElementById('leaderboard');
const podium = document.getElementById('podium');
const barChart = document.getElementById('barChart');
const storeFilter = document.getElementById('storeFilter');
const sortFilter = document.getElementById('sortFilter');
function prettyDate(iso){ if(!iso) return 'Resumen actualizado a fecha: pendiente'; const [y,m,d]=iso.split('-').map(Number); return `Resumen actualizado al ${dateFmt.format(new Date(y,m-1,d))}`; }
function initTabs(){ document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{ document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active')); document.querySelectorAll('.view').forEach(v=>v.classList.remove('active')); btn.classList.add('active'); document.getElementById(`view-${btn.dataset.view}`).classList.add('active'); })); }
function renderKpis(){ const s=data.summary||{}; const cards=[['Fecha de corte', prettyDate(data.updatedAt).replace('Resumen actualizado al ','')],['Líder actual',s.leader||'Pendiente'],['Dif. líder',`${(s.leaderDiff||0)>=0?'+':''}${num.format(s.leaderDiff||0)}`],['Unidades',num.format(s.totalUnits||0)],['Tiendas activas',`${s.participatingStores||0}/${(data.stores||[]).length}`]]; kpis.innerHTML=cards.map(([l,v])=>`<article class="kpi"><small>${l}</small><strong>${v}</strong></article>`).join(''); }
function fillFilters(){ (data.stores||[]).forEach(store=>{ const opt=document.createElement('option'); opt.value=store; opt.textContent=store; storeFilter.appendChild(opt); }); }
function rankIcon(rank){return rank===1?'🥇':rank===2?'🥈':rank===3?'🥉':`#${rank}`}
function trendText(r){ if(r.trend==='sube') return '↗ Tendencia arriba'; if(r.trend==='baja') return '↘ Revisar foco'; return r.difference>0?'✓ Sobre base':'→ En construcción'; }
function statusText(d){return d>8?'🔥 Ritmo ganador':d>2?'✅ Fuerte avance':d>0?'🟢 Sobre base':'🎯 Oportunidad'}
function getRows(){ let rows=[...(data.ranking||[])]; const store=storeFilter.value; if(store!=='all') rows=rows.filter(r=>r.store===store); const key=sortFilter.value; rows.sort((a,b)=>(b[key==='diff'?'difference':key]??0)-(a[key==='diff'?'difference':key]??0)); return rows; }
function renderPodium(){ const top=[...(data.ranking||[])].sort((a,b)=>a.rank-b.rank).slice(0,3); podium.innerHTML=top.map(r=>`<div class="podium-item"><img src="${r.image}" alt="${r.store}"><div><strong>${r.store}</strong><span>${statusText(r.difference)}</span></div><div class="podium-medal">${rankIcon(r.rank)}</div><div class="podium-diff">${r.difference>=0?'+':''}${num.format(r.difference)}</div></div>`).join(''); }
function renderChart(){ const rows=[...(data.ranking||[])].sort((a,b)=>b.difference-a.difference); const max=Math.max(1,...rows.map(r=>Math.max(0,r.difference))); barChart.innerHTML=rows.map(r=>{ const w=Math.max(3,Math.min(100,(Math.max(0,r.difference)/max)*100)); return `<div class="chart-row"><span title="${r.store}">${r.store}</span><div class="track"><div class="fill" style="width:${w}%"></div></div><div class="chart-value">${r.difference>=0?'+':''}${num.format(r.difference)}</div></div>`; }).join(''); }
function renderLeaderboard(){ const rows=getRows(); const maxDiff=Math.max(1,...(data.ranking||[]).map(r=>Math.max(0,r.difference))); leaderboard.innerHTML=rows.map((r,idx)=>{ const width=Math.max(3,Math.min(100,(Math.max(0,r.difference)/maxDiff)*100)); const diffClass=r.difference>=0?'positive':'negative'; return `<article class="rank-card ${r.rank===1&&storeFilter.value==='all'?'top1':''}" style="animation-delay:${idx*45}ms"><div class="photo-wrap"><div class="rank-badge">${rankIcon(r.rank)}</div><img src="${r.image}" alt="SM ${r.store}" loading="lazy"></div><div class="card-body"><div class="meta"><div><small>${statusText(r.difference)}</small><h3>${r.store}</h3></div><span class="trend">${trendText(r)}</span></div><div><div class="diff ${diffClass}">${r.difference>=0?'+':''}${num.format(r.difference)}</div><div class="progress"><div class="bar" style="width:${width}%"></div></div></div><div class="metrics"><div class="metric"><span>Base</span><strong>${num.format(r.base)}</strong></div><div class="metric"><span>Actual</span><strong>${num.format(r.current)}</strong></div><div class="metric"><span>Unidades</span><strong>${num.format(r.units)}</strong></div></div></div></article>`; }).join(''); }
function init(){ cutDate.textContent=prettyDate(data.updatedAt); initTabs(); renderKpis(); fillFilters(); renderPodium(); renderChart(); renderLeaderboard(); storeFilter.addEventListener('change',renderLeaderboard); sortFilter.addEventListener('change',renderLeaderboard); if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').catch(()=>{});} }
init();
